--CREATE PROCEDURE [dbo].[spUpdateUnitOffering]
--   @unitofferingid int,
--   @convenorid int,
--   @unitid int,
--   @teachingperiodid int,
--   @yearid int
--AS
--BEGIN
--   SET NOCOUNT ON;
--   UPDATE [dbo].[UnitOffering]
--   SET
      
--RETURN 0
